// Generated by CoffeeScript 1.9.1
var LinkedList, Node;

LinkedList = (function() {
  function LinkedList(head1) {
    this.head = head1;
  }

  LinkedList.prototype.toString = function() {
    var current, string, temp;
    current = head;
    return string = (function() {
      var results;
      results = [];
      while (current.val != null) {
        temp = current.val;
        current = current.next;
        results.push(temp);
      }
      return results;
    })();
  };

  LinkedList.prototype.insNode = function() {
    return "hello";
  };

  return LinkedList;

})();

Node = (function() {
  function Node(val, next, prev) {
    this.val = val;
    this.next = next;
    this.prev = prev;
  }

  return Node;

})();

module.exports = {
  LinkedList: LinkedList,
  Node: Node
};
