// Generated by CoffeeScript 1.9.1
var LinkedList, Node;

LinkedList = (function() {
  function LinkedList(head) {}

  LinkedList.prototype.toStringGarbage = function() {
    var current, string;
    current = head;
    return string = (function() {
      var results;
      results = [];
      while (current.val != null) {
        current = current.next;
        console.log(current.prev.val);
        results.push(current.prev.val);
      }
      return results;
    })();
  };

  LinkedList.prototype.removeNode = function() {
    return "hello";
  };

  return LinkedList;

})();

Node = (function() {
  function Node(val, next, prev) {
    this.val = val;
    this.next = next;
    this.prev = prev;
  }

  return Node;

})();

module.exports = LinkedList;

module.exports = Node;
