// Generated by CoffeeScript 1.9.1
var Node, Stack;

Stack = (function() {
  function Stack() {
    this.head = null;
  }

  Stack.prototype.push = function(node) {
    if (this.head != null) {
      this.head.prev = node;
      node.next = this.head;
      return this.head = node;
    } else {
      return this.head = node;
    }
  };

  Stack.prototype.pop = function() {
    var temp;
    if (this.head != null) {
      temp = this.head;
      this.head.next.prev = null;
      this.head = this.head.next;
      return temp;
    } else {
      throw new Error("Stack is empty");
    }
  };

  return Stack;

})();

Node = (function() {
  function Node(val, next, prev) {
    this.val = val;
    this.next = next;
    this.prev = prev;
  }

  return Node;

})();

module.exports = {
  Stack: Stack,
  Node: Node
};
